# Generated by Django 4.2.4 on 2023-08-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.TextField(blank='Ture', null=True, verbose_name='target')),
                ('title', models.TextField(verbose_name='title')),
                ('place', models.TextField(verbose_name='place')),
                ('date', models.TextField(verbose_name='date')),
                ('url', models.URLField()),
            ],
        ),
    ]
